<?php

$ObjectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helperData = $ObjectManager->create('Netreviews\Avisverifies\Helper\Data');
$storeId = $block->getStoreId();

// Only if reviews are displayed
if($helperData->getMainConfig('enabledwebsite',$storeId) == '1' && $helperData->getPlatformConfig('displayprodreviews',$storeId) == 'yes' && $helperData->getAdvancedConfig('add_reviews_to_product_page',$storeId) == '1') { ?>

<style type="text/css">

    /* ############################################################## */
    /* ####################### REVIEWS ############################### */
    /* ############################################################## */

    #idTabavisverifies {
        font-size: 14px;
        margin-top: 15px;
        color:#5d717e;
        background-color: #f7f7f7;
        border-radius:0px;
        padding-bottom: 15px;
    }
    #idTabavisverifies a {
        color:#5d717e;
        text-decoration: none;
    }
    #idTabavisverifies p {
        margin:0;
        padding:0; 
    }
    #idTabavisverifies div.ratingWrapper {
        height: 16px;
        width: 70px;
    }
    #idTabavisverifies div.ratingInner {
        height: 12px;
    }
    #idTabavisverifies .triangle-border {
        position: relative;
        padding: 12px;
        margin: 14px 0 3px 0;
        border: 2px solid #DDD;
        color: #000;
        background: #fff;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
    }
    #idTabavisverifies .triangle-border.answer {
        margin-left: 20px;
        color:#808080;
    }
    #idTabavisverifies .triangle-border.top::before {
        top: -16px;
        bottom: auto;
        right: auto;
        left: 46px;
        border-width: 0 14px 14px;
    }
    #idTabavisverifies .triangle-border::before {
        content: "";
        position: absolute;
        bottom: -20px;
        right: 40px;
        border-width: 20px 20px 0;
        border-style: solid;
        border-color: #DDD transparent;
        display: block;
        width: 0;
    }
    #idTabavisverifies .triangle-border.top::after {
        top: -13px;
        bottom: auto;
        right: auto;
        left: 47px;
        border-width: 0 13px 13px;
    }
    #idTabavisverifies .triangle-border::after {
        content: "";
        position: absolute;
        bottom: -13px;
        left: 47px;
        border-width: 13px 13px 0;
        border-style: solid;
        border-color: #fff transparent;
        display: block;
        width: 0;
    }
    #idTabavisverifies .triangle-border.answer {
        padding-left: 20px;
    }
    #idTabavisverifies #headerAV {
        display: block;
        background-color: #474747;
        height:30px;
        -webkit-border-top-left-radius: 10px;
        -webkit-border-top-right-radius: 10px;
        -moz-border-radius-topleft: 10px;
        -moz-border-radius-topright: 10px;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        text-align: center;
        line-height: 30px;
        color:white;
        text-transform: uppercase;
        font-size: 14px;
    }
    #idTabavisverifies #under-headerAV {
        display: block;
        height: 50px;
    }
    #idTabavisverifies div#aggregateRatingAV {
        list-style: none;
        margin-left: 50px;
        padding-top: 10px;
        float: left;
    }
    #idTabavisverifies div#certificatAV {
        float: right;
        list-style: none;
        padding-top: 5px;
        padding-right: 10px;
    }
    #idTabavisverifies .reviewAV {
        padding-bottom: 20px;
        border-top: 3px solid white;
    }
    #idTabavisverifies .reviewAV div.reviewInfosAV {
        list-style: none;
        margin-top: 15px;
        margin-left: 0;
        margin-right: 0;
        margin-bottom: 0;
    }
    #idTabavisverifies .reviewAV div.reviewInfosAV > div {
        display: inline-block;
        height: 25px;  
    }
    #idTabavisverifies .reviewAV div.reviewInfosAV  div.rateAV {
        font-weight: bold;
        font-size: 14px;
    }
    #idTabavisverifies .triangle-border.answer p.answer-bodyAV {
        margin: 10px 0 0 0 ;
    }
    #idTabavisverifies #netreviews_reviews_content {
        padding: 10px;
    }
    #netreviews_header_new {
        width:100%;
        padding:0px;
        margin:0px;
        display:block;
        margin-top:-15px;
    }
    #netreviews_header_new .netreviews_header_logo_new {
        float:left;
        min-width: 150px;
        max-width: 200px;
        width: 33%;
        height:auto;
        margin:15px 0px 0px 15px;
    }
    #netreviews_header_new .netreviews_header_link_new {
        float:right;
        margin:20px 20px 0px 0px;
        text-decoration:underline;
        color:#5d717e;
        font-size:15px;
        -webkit-box-shadow: none !important;
        box-shadow:none !important;
        outline:none;
    }
    #netreviews_header_new .netreviews_header_rate_text_new {
        width: 100%;
        display: block;
        text-align: center;
        margin: 0px;
        padding: 5px 0px;
        font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
        font-size: 40px;
        line-height: 40px;
        color: #555555;
    }
    #netreviews_header_new .netreviews_header_rate_comment_new {
        width: 100%;
        display: block;
        text-align: center;
        font-size: 13px;
        color: #5d717e;
        text-decoration: none;
        padding: 5px 0px 10px 0px;
    }
    #idTabavisverifies .display-all-comments {
        text-decoration:underline;
        color:#5d717e;
        font-size:15px;
        -webkit-box-shadow: none !important;
        box-shadow:none !important;
        outline:none;
        font-style:normal;
    }
    #av_load_next_page {
        text-decoration: none;
        float: none;
        display: block;
        padding: 4px 14px;
        font-size: 15px;
        line-height: 20px;
        color: #5d717e;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        background-color: #f5f5f5;
        border: 1px solid #5d717e;
        margin: 2px auto;
        font-weight: 500;
        border-radius: 0px;
    }
    #avisVerifiesAjaxImage {
        margin:10px auto;
    }
    .netreviewsclear {
        clear:both;
        font-size:1px;
        line-height:1px;
    }
    #avisVerifiesAjaxImage {
        display:none;
        margin: 5px auto 0px auto;
        width: 40px;
    }

    /* ############################################################## */
    /* ######################## STARS ############################### */
    /* ############################################################## */

    .netreviews-stars {
        padding: 0px;
        /*width: 100%;*/
        display: block;
        height: 25px;
        border: none;
        margin: 8px auto;
    }
    .netreviews-stars .netreviews_bg_stars {
        float: left;
        display: block;
        width: 80px;
        min-width: 80px;
        max-width: 80px;
        height: 17px;
        min-height: 17px;
        max-height: 17px;
        margin: 0px;
        padding: 0px;
        border: none;
        background-image: url('<?php echo $this->getViewFileUrl('Netreviews_Avisverifies::images/stars/star-empty-16.png'); ?>');
        background-repeat: repeat-x;
        background-position: left center;
        text-decoration: none;
        outline: none;
    }
    .reviewInfosAV .netreviews-stars .netreviews_bg_stars{
        margin: 0px 5px;
    }
    .netreviews_bg_stars span {
        display: block;
        min-width: 0px;
        max-width: 80px;
        height: 17px;
        min-height: 17px;
        max-height: 17px;
        margin: 0px;
        padding: 0px;
        border: none;
        background-image: url('<?php echo $this->getViewFileUrl('Netreviews_Avisverifies::images/stars/star-gold-16.png'); ?>');
        background-repeat: repeat-x;
        background-position: left center;
        text-decoration: none;
        outline: none;
        line-height: 1px;
        font-size: 0.1px;
    }
    .netreviews_header_rate_stars_new .netreviews_bg_stars span {
        max-width: 120px;
    }
    .netreviews-stars a, .netreviews-stars a:hover, .netreviews-stars a:active, .netreviews-stars a:visited {
        line-height: 22px;
        font-size: 14px;
        display: block;
        text-decoration: underline;
        border: none;
        box-shadow: none;
        margin: 0px 0px 0px 8px;
        float: left;
        cursor: pointer;
    }
    .netreviews_bg_stars_big {
        margin: 3px auto;
        width: 120px;
        min-width: 120px;
        max-width: 120px;
        height: 24px !important;
        min-height: 24px !important;
        max-height: 24px !important;
        background-image: url('<?php echo $this->getViewFileUrl('Netreviews_Avisverifies::images/stars/star-empty-24.png'); ?>');
    }
    .netreviews_bg_stars_big_gold span {
        background-image: url('<?php echo $this->getViewFileUrl('Netreviews_Avisverifies::images/stars/star-gold-24.png'); ?>');
        height: 24px !important;
        min-height: 24px !important;
        max-height: 24px !important;
    }

    /* ############################################################## */
    /* ###################### RESPONSIVE ############################ */
    /* ############################################################## */
    
    @media screen and (max-width: 700px) {
        #netreviews_header_new {
            text-align:center;
        }
        #netreviews_header_new .netreviews_header_logo_new {
            float:none;
            margin:10px auto;
        }
        #netreviews_header_new .netreviews_header_link_new {
            float:none;
            display:block;
            width:100%;
            margin:5px auto;
        }
    }

</style>

<?php } ?>